name: reusable workflow for log cleanup
description: Use for cleanup log files

on:
  workflow_call:
    inputs:
      repo-name:
        description: The repo name.
        required: true
        type: string

jobs:
  
  cleanup:
    runs-on: ubuntu-latest
      
    steps:
    - name: execute cleanup commands
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        echo "Cleaning up log files in ${{ inputs.repo-name }}"
        $workflowRuns = gh api repos/${{ inputs.repo-name }}/actions/runs --paginate --jq 'select(.status != "queued") | workflow_runs[].id'
        foreach($runId in $workflowRuns){gh api repos/${{ inputs.repo-name }}/actions/runs/$runId -X DELETE}
      shell: pwsh

