name: reusable workflow for log cleanup
description: Use for cleanup log files

on:
  workflow_call:
    inputs:
      repo-owner:
        description: The repo owner name.
        required: true
        type: string
      repo-name:
        description: The repo name.
        required: true
        type: string

jobs:
  
  cleanup:

    runs-on: ubuntu-latest

    steps:

    - name: execute cleanup commands       
      run: |
        echo "Cleaning up log files in ${{ inputs.repo-owner }}/${{ inputs.repo-name }}"
        # Add your log cleanup commands here
      shell: bash

