name: reusable workflow for log cleanup
description: Use for cleanup log files

on:
  workflow_call:
    inputs:
      repo-name:
        description: The repo name.
        required: true
        type: string

jobs:
  
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

  cleanup:
    runs-on: ubuntu-latest
    continue-on-error: true  
    steps:
    - name: execute cleanup commands
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        echo "Cleaning up log files in ${{ inputs.repo-name }}"
        $workflowRuns = gh api repos/${{ inputs.repo-name }}/actions/runs --paginate --jq '.workflow_runs[].id'
        foreach($runId in $workflowRuns){gh api repos/${{ inputs.repo-name }}/actions/runs/$runId -X DELETE}
      shell: pwsh

